# ----------------------------------------------------
# General Book Info
# ----------------------------------------------------
title: CiTG Jupyter Book template
author: TU Delft
logo: images/TUDelft_logo_rgb.png
copyright: Delft University of Technology
book_version: "1.0.0"

# ----------------------------------------------------
# Launch Buttons (Enable Thebe)
# ----------------------------------------------------
launch_buttons:
  thebe: true

# ----------------------------------------------------
# Notebook Execution Settings
# ----------------------------------------------------
execute:
  execute_notebooks: "auto"
  include_output: true
  include_widgets: true
  include_plotlyjs: true

# ----------------------------------------------------
# HTML / JS Settings
# ----------------------------------------------------
html:
  scripts:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    - https://cdn.plot.ly/plotly-latest.min.js
  comments:
    hypothesis: true

# ----------------------------------------------------
# Sphinx Settings
# ----------------------------------------------------
sphinx:
  extensions:
    - jupyter_sphinx
    - nbsphinx
    - sphinx_togglebutton
    - sphinx_copybutton
    - sphinx.ext.mathjax
    - sphinx_exercise
  config:
    # Ensures interactive cells can fetch JS properly
    jupyter_sphinx_require_url: true

    # Bibliography styling
    bibtex_reference_style: author_year_round
    bibtex_default_style: myapastyle

    # Use MathJax 3 for LaTeX rendering
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

    # Thebe config
    thebe_config:
      use_thebe_lite: true

# ----------------------------------------------------
# Bibliography
# ----------------------------------------------------
bibtex_bibfiles:
  - references.bib

# ----------------------------------------------------
# MyST Parser (for extended Markdown + LaTeX)
# ----------------------------------------------------
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

# ----------------------------------------------------
# Jupyter Widget Support
# ----------------------------------------------------
jupyter:
  jupyter_widgets: true
