name: call-deploy-book

on:
  push:
    branches:
      - '**'
    paths:
      - book/**
      - requirements.txt
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs: 
  call-workflow:
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

  add-nojekyll:
    needs: call-workflow  # Ensures this runs AFTER the main deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add .nojekyll to prevent GitHub Pages from ignoring underscores
        run: touch book/_build/html/.nojekyll

      - name: Commit and push .nojekyll
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add book/_build/html/.nojekyll
          git commit -m "Add .nojekyll to prevent Jekyll processing" || echo "No changes to commit"
          git push
